/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayDeque;

public class App {

    public static void main(String[] args) {

        ArrayDeque<DailyTerm> termsList = DAL.showTerms();
        for (DailyTerm term : termsList) {
            System.out.println(term.getTerm());
        }
        System.out.println("\nend test");

        
    }
}
